### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by Akujiism**

### CODE REVIEW

**Comment by Akujiism** [comment]
Russian translation

**Comment by humdingerb** [comment]
Thanks for the PR!

Could you add this under the code of the Russian menu item, so it reads:
```
<li class="now"><img src="../images/flags/ru.png" alt="" /> Русский</li>
<li><a href="../en/01-start.html"><img src="../images/flags/gb.png" alt="" /> English</a></li>
```
On every page, replacing the file name with the one of the page (../en/01-start.html).

Will you provide screenshots with the Russian locale as well? We can do that in another PR.

**Comment by Akujiism** [comment]
> Could you add this under the code of the Russian menu item, so it reads:

Done.
 
> Will you provide screenshots with the Russian locale as well? We can do that in another PR.

I've updated the first two screenshots with translating the English text to Russian. I'm not good at taking and editing screenshots so it's better for someone else to do this.

**Comment by humdingerb** [comment]
Thanks. I'll see if I can shoot the screens in Russian when I do the German ones.

**Pull request merged**
